apiVersion: apps/v1
kind: Deployment
metadata:
 name: java-calculator-deployment
spec:
 selector:
   matchLabels:
     app: java-calculator
 replicas: 2 # tells deployment to run 2 pods matching the template
 template:
   metadata:
     labels:
       app: java-calculator
   spec:
     containers:
     - name: java-calculator
       image: madhurimabb/backstage-image:latest
       ports:
       - containerPort: 80
