apiVersion: v1
kind: Service
metadata: 
 labels: 
   app: java-calculator
 name: java-calculator-service
 namespace: default
spec: 
 ports: 
 - port: 80
   protocol: TCP
   targetPort: 80
 selector: 
   app: nginx
 type: NodePort
