name: Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
       username: ${{ vars.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backstage-image:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/backstage-image:latest

    - name: Set up kubectl to use Minikube
      run: |
        mkdir -p $HOME/.kube
        mkdir -p $HOME/.minikube
        cp -R /mnt/c/Users/User/.kube $HOME/.kube
        cp -R /mnt/c/Users/User/.minikube $HOME/.minikube
        sudo chown -R $USER $HOME/.kube $HOME/.minikube
        kubectl config use-context minikube

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl rollout status deployment/java-app
