name: Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
       username: ${{ vars.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: madhurimabb/backstage-image:latest
        context: .
    - name: Set up kubectl to use Minikube
      run: |
        mkdir -p $HOME/.kube
        mkdir -p $HOME/.minikube
        cp -R ~/.kube $HOME/.kube
        cp -R ~/.minikube $HOME/.minikube
        sudo chown -R $USER $HOME/.kube $HOME/.minikube
        kubectl config use-context minikube

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl rollout status deployment/java-app
